# Generated by Django 4.2.24 on 2025-09-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(db_column='CartID', primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
            ],
            options={
                'db_table': 'Cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cartitems',
            fields=[
                ('cartitemid', models.AutoField(db_column='CartItemID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
            ],
            options={
                'db_table': 'CartItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryid', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderitems',
            fields=[
                ('orderitemid', models.AutoField(db_column='OrderItemID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'OrderItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(db_column='OrderID', primary_key=True, serialize=False)),
                ('orderdate', models.DateTimeField(blank=True, db_column='OrderDate', null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=20, null=True)),
                ('totalamount', models.DecimalField(blank=True, db_column='TotalAmount', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('paymentid', models.AutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10)),
                ('paymentdate', models.DateTimeField(blank=True, db_column='PaymentDate', null=True)),
                ('method', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Method', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productid', models.AutoField(db_column='ProductID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=200)),
                ('description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', null=True)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(blank=True, db_column='Stock', null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('updatedat', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
            ],
            options={
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviewid', models.AutoField(db_column='ReviewID', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, db_column='Rating', null=True)),
                ('comment', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Comment', null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
            ],
            options={
                'db_table': 'Reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FullName', max_length=150)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=150, unique=True)),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Password', max_length=255)),
                ('phone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Phone', max_length=20, null=True)),
                ('role', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Role', max_length=20, null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('updatedat', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('shopname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ShopName', max_length=150, null=True)),
                ('bio', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Bio', null=True)),
                ('address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Address', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='State', max_length=100, null=True)),
                ('country', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Country', max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Pincode', max_length=20, null=True)),
                ('aadhaarno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AadhaarNo', max_length=12, null=True, unique=True)),
                ('panno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PANNo', max_length=10, null=True, unique=True)),
                ('imagepath', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
